// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjeldhehnleklaafioto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqZWxkaGVobmxla2xhYWZpb3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ2MDMsImV4cCI6MjA2NTQ3MDYwM30.CcG4HDHbf8vP3WHaZXoBVQ4r08H6jsKzPYF8bsYfRgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);